### PR TITLE
Update to support Paho C v1.3.6

### PR DESCRIPTION
**Pull request by svanharmelen**
As I needed this update for myself anyway, I thought to just make a PR for it. I turned off the formatter in my editor, so the changes are limited to functional changes except for the changes in `create_options.rs`.

I needed to update that file, but noticed that it used both tabs and spaces for indentation (at the same time). So next to the functional changes (which are the lines from 279 to 306) the only thing I also did was changing the tabs into spaces to make the indentation consistent within the  `create_options.rs` file.

### CODE REVIEW

**Comment by svanharmelen** [comment]
This should solve #99

**Comment by svanharmelen** [comment]
Probably we would want to update this to `v1.3.7` (whenever that is released) before merging it into the upcoming `v0.8`, as that fixes a few issues (https://github.com/eclipse/paho.mqtt.c/issues/972). I'll keep an eye on the C package and update this PR when `v1.3.7` is released.

**Comment by fpagliughi** [comment]
Thanks so much for the PR! Apologies for the slow response; been trying to get the C++ lib out first. 

Unfortunately I had already started on a bunch of this work and hadn't pushed it, so this looks like a troublesome merge. I'll try to get it done or enlist your help. I should have the C++ lib out soon and then refocus on this one. And it does appear that v1.3.7 will be out this week, so that will be the target.

**Comment by fpagliughi** [comment]
OK. I'm starting to work on this. I will let you know how it goes.

**Comment by svanharmelen** [comment]
Sounds good 👍🏻 I'm available in case you have any questions...

And just to be clear, I don't mind if you don't use this PR and only copy bits and pieces that your can use if that is easier. To me it only matters that this code gets merged, not that my name is in the commit message 😉

**Comment by fpagliughi** [comment]
Oh, I should mention, two things have come up...

1. There's a new Paho C lib coming out, hopefully within the next few days. v1.3.7   That will be the target. It has http/websocket proxy support that I need.

2. The new stuff to be added will be a breaking change from what's currently in _master_.

I know a lot of people have started using _master_ in the last few months because of async/await and also some problems with building 0.7.

So my thinking at the moment is to just push out what's in _master_ as v0.8 and then start working on all the new features and breaking changes as v0.9, which would then come out in a few weeks.

**Comment by svanharmelen** [comment]
> There's a new Paho C lib coming out, hopefully within the next few days. v1.3.7

Yeah I was waiting for that one. Nice!

> That will be the target. It has http/websocket proxy support that I need.

Are you kidding me! I have an issue on our backlog for this sprint to test if we can proxy our websocket MQTT traffic 😄 You just became the hero of the week 😉 

> The new stuff to be added will be a breaking change from what's currently in master.

Check... For me that is not a problem as I'm currently using a fork that has the SSL PR, this PR and a couple of other tweaks added to it.

> So my thinking at the moment is to just push out what's in master as v0.8 and then start working on all the new features and breaking changes as v0.9, which would then come out in a few weeks.

I guess that would indeed be nice for people who currently use master 👍🏻 As for the timelines, my fork is working fine for us but like I just said we are planning to switch our traffic over a proxy and we have some external push (the other outbound connections are getting shut) for that. So good to keep in contact so we don't do stuff twice (as I will try to implement it myself if you are too busy).

Thanks!

**Comment by fpagliughi** [comment]
@svanharmelen Can you just re-submit this against the `develop` branch, and I will get it right in.

**Comment by svanharmelen** [comment]
Yup, will do 👍🏻

**Pull request closed without merging**
