### PR TITLE
Make the publish call return a result

### PR DESCRIPTION
**Pull request by svanharmelen**
Potential solution for #101

Signed-off-by: Sander van Harmelen <sander@vanharmelen.nl>

### CODE REVIEW

**Comment by svanharmelen** [comment]
I'm using it like this for a while now, and it works really nice. What is your take on this @fpagliughi? Is this something that can be merged?

**Comment by svanharmelen** [comment]
@fpagliughi how are things going? Do you have any feedback on this PR? Can it be merged as is, or do you like me to make any changes first?

**Comment by fpagliughi** [comment]
Hi @svanharmelen . This for this PR and the others.

I like and understand the idea for this change, but I don't think it should go into the library for two reasons...
1) It then requires everyone to check twice for errors instead of just once.
2) It breaks with the other Paho libraries that use futures-style return values - and I work with a bunch of people who maintain similar code bases in multiple languages.

I just wonder if there's something better we can do to allow people to check for immediate errors in the returned token if they want, without forcing everyone to do two error checks.

Since issue #101 has a good description of the problem being addressed, let's discuss there.

**Comment by svanharmelen** [comment]
Seems this will not make it in, so I'll close it again 😏

**Pull request closed without merging**
