### PR TITLE
Transition to 2018 edition

### PR DESCRIPTION
**Pull request by tobdob**
Transition to 2018 edition using:
`cargo fix --edition`
`cargo fix --edition-idioms`
+ some manual fixes

Signed-off-by: Tobias Dubois <tobias.dubois@gmail.com>

### CODE REVIEW

**Comment by fpagliughi** [comment]
@tobdob, Thanks so much for this pull request. At the moment I'm pretty deep into implementing the MQTT v5 features, which I hope to release by the end of the year. I need to keep 2015 for this next release for a couple reasons. I haven't had the time to familiarize myself with the 2018 features; I know of several commercials users of the library who are stuck on an older compilers (due to validation); and the upgrade to v5 is pretty involved and I want to limit the other changes.

So I will first get out the next v5 release (crate v0.7), and will look to merge this in for the following release (v0.8). At that time I will also start looking into updating the futures library.

I will update the milestones to put this plan all together.

**Comment by tobdob** [comment]
Ok, thanks for the update!
My main motivation for this change was to prepare for async/await support.

**Comment by fpagliughi** [comment]
Yeah, I'm looking forward to async/await, but I do want it to settle down a bit before making a big effort to add support. Plus I know that this crate is being used in some commercial systems, and we need to be careful about big breaking changes before stabilizing the old version.

MQTT v5 adds some great features and the API will be pretty backward compatible with the existing release. Maybe when that is fairly stable in a couple weeks we can throw this into a branch and start playing with some new Rust features.

**Comment by tobdob** [comment]
I have been using async/await with the futures compat layer and it is working well so far, so I'll survive for a while :)

**Comment by fpagliughi** [comment]
Thanks again for this PR! Sorry it took me so long to get in there. I had to manually merge it, but it's now in the `asyncawait` branch.

**Pull request closed without merging**
