### PR TITLE
Run `cargo fmt —all` on the project

### PR DESCRIPTION
**Pull request by svanharmelen**
I was making a change in this package as preparation for a PR, but noticed a lot of changes were caused by my editor (which is configured to format the file on save using the rust-analyzer).

So before making any functional changes, I thought to just make a PR which only contains the changes caused by running `cargo fmt --all`. So to be clear, I made **no** functional changes. These are all **only** formatting changes.

### CODE REVIEW

**Comment by svanharmelen** [comment]
@fpagliughi would it be possible to merge this one? Or do you have any objections or feedback to discuss first? Thanks!

**Comment by fpagliughi** [comment]
I'm pretty close to a release, but still have a number of unmerged branches which may or may not make it in. I just don't want to reformat the source and then have merge headaches at this point in the release cycle. Plus the added debug and test from touching all the sources - although it has been a long time since _rustfmt_ actually destroyed any of my code.

But I do appreciate you submitting it as a stand-alone PR! That's helpful.

At this point, I want to get the release out first, then we can look at a reformat. I also tend to use a few variations via _.rustfmt.toml_. We can discuss those as well.

**Comment by svanharmelen** [comment]
Hmm... Ok... The problem/challenge (for me then :wink:) is that whenever I want to make a change, my editor automatically re-formats everything. So that means that I have to reconfigure my editor setup in order to be able to make a PR that only contains a functional change.

But besides that, I do think it's a good idea to merge this before making the 0.8 release, so that the new release is off to a clean start. And of course if you would merge this now already, the merge conflicts in any of those potential branches would be easily solved by running `cargo fmt --all` on those branches as well 😏 

As for any variations using _.rustfmt.toml_, I have no opinions on that one. As long as it's automatically handled by the `fmt` command and so the code is consistent and can easily be updated, I'm good.

**Comment by svanharmelen** [comment]
Not related to this PR, but I just reached out to you on Mattermost to discuss the functional PR I was referring to. I think it makes sense to first discuss that one synchronous before I make the PR... But let me know if you think otherwise. Thanks.

**Comment by fpagliughi** [comment]
I have no problem in you calling me out for non-standard formatting in the project - especially since _rustfmt_ works well now, and I should have reformat the code a while ago.

But in general, you should turn the reformatting feature off in your editor whenever you work on a PR for someone else's open-source project - or at least limit it to the lines that you're modifying. Despite a recommended standard, I still see quite a few Rust projects that have numerous author formatting quirks in them.

**Comment by svanharmelen** [comment]
I agree... That's also why I mentioned it was my "problem/challenge". And didn't mean to "call you out"! Sorry if it came across like that.

**Comment by fpagliughi** [comment]
Didn't mean it in a bad way.

**Comment by svanharmelen** [comment]
Is there any chance that this one (of course possibly tweaked/updated so it uses a custom `.rustfmt.toml` as you hinted on earlier) could also be part of the upcoming v0.8 release?

**Comment by svanharmelen** [comment]
Are you open to this one now (as v0.8 is released), but then against the `develop` branch?

The Rust plugin for CLion (I don't know if you use CLion but I expect you do considering you do a lot in C++ as well) now also supports using rustfmt, so it looks like the community is slowly trying to converge to this formatting style:

image

Think it would be great if we can update this project as well...

**Comment by svanharmelen** [comment]
FYI if your not open for this I respect that! Just let me know so we can either close this PR and be done with it, or close this PR and open a new one against `develop`. Thanks!

**Comment by fpagliughi** [comment]
Unfortunately this PR is getting stale, and it would probably be more difficult to merge than to just reformat the codebase at some point.

I have two issues, though, which are on me:
- There are a few (minor) issues that I would prefer to adjust, and those adjustments in _rustfmt_ seem to still be marked as _nightly_.
- My editor doesn't yet support _rustfmt_ and would be fighting it. That would probably give me headaches.

So I still think this is the proper thing to do, once again, I would like to defer until after the burst of activity to see if I can (or the tool can) help me fix these two issues.

What we should probably do is close the PR and put up and issue for the same thing to remind me. :smile:

**Comment by svanharmelen** [comment]
All good... Then I'll close this one for now 👍🏻

**Pull request closed without merging**
