### PR TITLE
#10 Properly destroy the underlying MQTTAsync handle by calling MQTTA…

### PR DESCRIPTION
**Pull request by jnicholls**
…sync_destroy in the implementation of AsyncClient::drop.

### CODE REVIEW

**Comment by jnicholls** [comment]
I have signed the ECA and am awaiting an approval. I'll let you know when it's approved for manual verification (or I can force a re-check by amending my commit and force pushing...at least I think that would do the trick).

**Comment by fpagliughi** [comment]
Awesome. I should be able to see when your ECA clears. I'll keep an eye out for it.

**Comment by jnicholls** [comment]
It has cleared, you can search for `jarred.nicholls@gmail.com`

**Comment by fpagliughi** [comment]
Hey @jnicholls, I manually confirmed your email in the ECA in the Eclipse database. Thanks!  

But the automated ip-validation check on this pull request is still showing a failed check, and I can't merge until it passes. Is the 'goefer' GitHub account registered to your same e-mail as submitted for the ECA?

Maybe if we wait a day, it will percolate through the system. If not, perhaps you can try to resubmit then.

**Comment by fpagliughi** [comment]
And one other thing... as discussed in PR #13, the persistence object **must** outlive the underlying C client, because `MQTTAsync_destroy()` calls close on the persistence object. 

So the `MQTTAsync_destroy()` call should happen before the call to `drop(Box::from_raw(self.persistence_ptr));`

**Comment by jnicholls** [comment]
>And one other thing... as discussed in PR #13, the persistence object must outlive the underlying C client, because MQTTAsync_destroy() calls close on the persistence object.

>So the MQTTAsync_destroy() call should happen before the call to drop(Box::from_raw(self.persistence_ptr));

WRT the ip-validation check, it's not going to re-check unless I modify the PR, so I'll amend the PR to move the destroy call to before the persistence drop.

**Comment by jnicholls** [comment]
I'm going to attempt closing this PR and opening a new one to see if the ECA check will be performed.

**Comment by jnicholls** [comment]
Ok, so I tried from `goefer` as well as my personal fork, and the ip-validation just isn't working. It's throwing an error and saying to contact support when I try to view the details...so I guess we wait? I'm surprised you aren't able to forcibly merge a PR, I've never seen a PR hook that could not be ignored by the admin of the repository and PRs be merged regardless of validation checks.

**Comment by fpagliughi** [comment]
It's a legal issue, not a technical one. I could _force_ the merge, but then the Eclipse lawyers could reject the release. Or it would make their lives harder as they would need to manually confirm each forced merge.

Apologies for the pain. I'll check with Eclipse IT.

**Comment by jnicholls** [comment]
No worries, I understand! Thanks for contacting them, I hope they know what's going on. In the meantime, does the PR look sound now with the proper drop order and the additional drop of the ClientPersistence context?

**Comment by fpagliughi** [comment]
Yes. I got a message from the Eclipse webmaster on Mon:
```
 We've been having some issues with the CLA validator and are trying to figure out what's happening.
```
This is still showing as failing ip-validation. But the PR from @siscia on Sun (#19) passed validation, even though his earlier ones are shown as failing. 

Can I trouble you to try one more re-submit of this? If that doesn's pass, I'll force it in.

**Comment by jnicholls** [comment]
@fpagliughi Yep, I just amended the commit and the validation check passed now. Sweet!

**Comment by jnicholls** [comment]
@fpagliughi Can you merge this when you get a chance? Thanks. Also 1.3.0 of paho.mqtt.c is out so this lib should merge in or copy the PRs that get it 1.3.0 compatible.

**Comment by fpagliughi** [comment]
@jnichols: As for Paho v1.3, see #20

**Comment by jnicholls** [comment]
Awesome, thanks!

**Pull request merged**
