### PR TITLE
Update to support Paho C v1.3.6

### PR DESCRIPTION
**Pull request by svanharmelen**
As I needed this update for myself anyway, I thought to just make a PR for it. I turned off the formatter in my editor, so the changes are limited to functional changes except for the changes in `create_options.rs`.

I needed to update that file, but noticed that it used both tabs and spaces for indentation (at the same time). So next to the functional changes (which are the lines from 279 to 306) the only thing I also did was changing the tabs into spaces to make the indentation consistent within the  `create_options.rs` file.

### CODE REVIEW

**Comment by fpagliughi** [comment]
Thanks @svanharmelen !

**Comment by svanharmelen** [comment]
That was quick 😄  Thanks!

**Comment by fpagliughi** [comment]
BTW, this looks pretty good. Thanks again.

One thing I found, though, was that the SSL ALPN "protos" implementation appeared to be leaking memory. The C lib is somewhat inconsistent in how it handles option data, so to be safe, I typically use a Rust/ffi object to hold the data, and then set the C pointers to those objects. So for example, if the struct expects a `const char*`, I keep an `ffi::CString` in the options struct, and set the C pointer to its internal array.

So I created a `protos: Vec<c_uchar>` field in `SslOptionsData` to hold the string instead of forgetting it.
That's up in the develop branch now.

**Comment by svanharmelen** [comment]
Check... Good to know and that’s a nice solution 👍🏻

Also noticed the C lib was just released. Super nice to see all this progress 🙂

**Comment by fpagliughi** [comment]
Yeah, I knew the C lib was coming... but nice surprise for it to pop up right as I was working on the version upgrade. I'm already switching to the new bindings and started to work on the Proxy stuff today!

**Pull request merged**
