### PR TITLE
Automatically locate Homebrew OpenSSL on macOS

### PR DESCRIPTION
**Pull request by rajivshah3**
On macOS, many people install OpenSSL from Homebrew. This PR allows them to build the library without having to specify `OPENSSL_ROOT_DIR` since we can find that path by running `brew --prefix openssl`:

```
$ brew --prefix openssl
/usr/local/opt/openssl@1.1
```

This addresses https://github.com/eclipse/paho.mqtt.rust/issues/75#issuecomment-640178989

### CODE REVIEW

**Comment by svanharmelen** [comment]
Hi @rajivshah3! Just as a heads up; PR #92 (which was merged in the `develop` branch last week) introduces the use of the `openssl-sys` crate to find or compile openssl. The `openssl-sys` crate contains logic to search for well known locations for all major operating systems, so that includes searching for brew installed versions on macOS...

**Comment by rajivshah3** [comment]
Oh, nice! I didn't realize there was a `develop` branch. In that case I can close this. Thanks for that PR!

**Comment by rajivshah3** [comment]
Hi @fpagliughi , do you think you could release a new version with the changes from #92? We're using this library in a few of our projects and I think the `openssl-sys` will make things a bit easier

**Comment by fpagliughi** [comment]
The next release, v0.9, is in the works right now. It's due by the end of Dec, but hopefully will not take that long. 

I need to make sure #92 is stable, though, as it's doing something weird for me when cross-compiling. I'll  start a discussion to resolve it soon.

There is also a minor problem in the latest C lib, but it might hold us up. Hopefully not. See #99 with details on the C lib upgrade.

**Comment by rajivshah3** [comment]
Ok, thanks for the update!

**Comment by svanharmelen** [comment]
@fpagliughi from what host to which target are you cross compiling and what issues do you see? Maybe I can help resolve them as I'm using this setup for a while now (also for cross compiling)...

**Comment by svanharmelen** [comment]
We can talk on Mattermost as well if that's more convenient.

**Comment by fpagliughi** [comment]
I though I would open an issue for it when I have more information. My initial test was on an x86_64 host compiling for an ARMv7 target, and it appeared to link to two separate versions of GLIBC. Weird.

**Comment by svanharmelen** [comment]
Which options/features did you use (if any)? If I know the compile options/features I can compare/test...

**Comment by fpagliughi** [comment]
Just the default with vendored SSL, I think.

**Pull request closed without merging**
