### PR TITLE
Some clippy fixes

### PR DESCRIPTION
**Pull request by qm3ster**
~~A bit more are on the way.~~ **Edit:** ye, am done now. The rest require bikeshedding, maybe even conscious thought.

Stuff like
```rust
match tok.try_wait() {
    //Some(Err(Error::Paho(ERR_CODE))) => (),
    Some(Err(Error::PahoDescr(ERR_CODE, _))) => (),
    Some(Err(_)) => assert!(false),
    Some(Ok(_)) => assert!(false),
    None => assert!(false)
}
```
I changed to
```rust
match tok.try_wait() {
    //  Some(Err(Error::Paho(ERR_CODE))) => {}
    Some(Err(Error::PahoDescr(ERR_CODE, _))) => {}
    Some(Err(_)) | Some(Ok(_)) | None => unreachable!()
}
```
because
```rust
assert_matches!(tok.try_wait().unwrap_err(), Error::PahoDescr(ERR_CODE, _));
```
or
```rust
assert_matches!(tok.try_wait(), Err(Error::PahoDescr(ERR_CODE, _)));
```
is not stable yet

### CODE REVIEW

**Comment by qm3ster** [comment]
I am likely done for this week... or this life? Peace out!

And remember - never squash marge, think of the children.

**Comment by fpagliughi** [comment]
Merged into the `develop` branch.

**Comment by qm3ster** [comment]
@fpagliughi do you have anywhere to communicate synchronously? Ideally Discord, the other people are on there.

**Comment by fpagliughi** [comment]
I do have a Discord account, but don't use it much, and Eclipse/Paho has not set up any official channel for us to use on it. There is a Mattermost channel and email list for the project as linked in the README. All discussion about the project should be kept open and public.

**Pull request closed without merging**
