### PR TITLE
feature: Allow OpenSSL to be linked statically

### PR DESCRIPTION
**Pull request by rajivshah3**
This PR (similar to #72) allows the library to statically link OpenSSL instead of dynamically by setting the `OPENSSL_LINK_STATIC` env var. This allows users of the library to ship it with their applications without requiring the end user to install OpenSSL

### CODE REVIEW

**Comment by svanharmelen** [comment]
Hi @rajivshah3! I'm afraid this is also already added/fixed by PR #92. The `openssl-sys` crate contains a lot of flags that allow you to tweak how it compiles, see https://docs.rs/openssl for more details.

For this specific option (static linking) it contains this option:

```
OPENSSL_STATIC - If set, the crate will statically link to OpenSSL rather than dynamically link.
```

**Comment by fpagliughi** [comment]
Hmm. That is something I hadn't thought of...

Is the openssl-sys crate always linking in an outside library?  Or will it look for a valid library in the build (or cross-build) environment, and use that if available?

**Comment by fpagliughi** [comment]
Oh, wait, I think I see it...

If we use the "ssl" feature it uses `openssl-sys` in non-vendored mode,
If we use "vendored-ssl" is uses `openssl-sys` and passes it the vendored feature flag.

So I believe @svanharmelen is correct. Using `openssl-sys` we don't need this PR or #74. Both are covered by using `openssl-sys`.

**Comment by rajivshah3** [comment]
My bad, I should have checked that first. Thanks!

**Comment by fpagliughi** [comment]
Thanks for the PR, though. I appreciate the help!

**Pull request closed without merging**
