### PR TITLE
Further random changes to the code with no reason or purpose

### PR DESCRIPTION
**Pull request by qm3ster**
(but also no bad consequences)

### CODE REVIEW

**Comment by fpagliughi** [comment]
Hey. Thanks for the PR. I'm really busy with work, so may not get to this until the weekend (or random late night!)

After a quick glance, I think I'll probably look at the commits separately and cherry pick. For example, I definitely want to keep the `let _ = into_raw()` lines. To me that's a clear hint that I am extracting a value and purposely ignoring it. There are a few similar things that I prefer to be explicit about. 

But the mutex guards and extraneous return fixes look good.

**Comment by qm3ster** [comment]
Might I suggest `drop(unsafe { Token::from_raw(lkopts.copts.context) });` then?

**Comment by fpagliughi** [comment]
I'm fine with `let _ = ...`
It seems pretty idiomatic.

**Comment by fpagliughi** [comment]
I cherry-picked about half of this into the "develop" branch.

**Comment by fpagliughi** [comment]
Thanks, again!

**Comment by qm3ster** [comment]
I only see `let _ =` used when:
- one needs to assert the type, like `let _: X =`, for example it can't be inferred.
- they want to suppress `#[must_use]` warnings, such as calling a side effectful function that returns `Result`. Like `write` that returns bytes written + there aren't measures to take if there was an error.

When non `#[must_use]` are ignored, they're just not assigned.

And when something is constructed (eg from pointers) just to drop it I've seen `drop()`, but to be fair I've seen `let _ =` for this before too.
Main use of `drop()` does remain dropping guards or freeing borrows without creating a block scope.

**Comment by qm3ster** [comment]
Why not a2ec10b and db3cf8a?

**Comment by fpagliughi** [comment]
For `let _ =` I ripgrep'ed through a bunch of std library code, and perhaps it's not as common as I had assumed, but it is used in cases to seemingly indicate that something is being returned that is being ignored, even in cases where the return value is not a `Result<>` or something that must be used. For example the Unix file descriptor drop:

```
impl Drop for FileDesc {
    fn drop(&mut self) {
        // Note that errors are ignored when closing a file descriptor. 
        // ...
        let _ = unsafe { libc::close(self.fd) };
    }
}
```

I like the usage, and the fact that "_" doesn't bind the return value is a perfect match for what I want: To remind myself that na important value is being returned and that I specifically don't care.

**Comment by fpagliughi** [comment]
https://github.com/eclipse/paho.mqtt.rust/commit/a2ec10bc06df68b68a331238fc3532d679815906 is in there. It just hit a merge conflict and when I fixed them and commit, it created a new commit, which I brilliantly lbeled "merge".

For https://github.com/eclipse/paho.mqtt.rust/commit/db3cf8ac7a74180589508270582f884414b95b47 I simply prefer the more explicit original version to remind everyone what, exactly, is being created.

**Pull request closed without merging**
