### PR TITLE
Fixed #7: Missing fields on build

### LINKED ISSUE #7: Missing fields on build
Hi, I'm trying to build paho.mqtt.rust but I get a field missing error during compilation.

This error is against `paho.mqtt.c` master branch, but I also tried v1.2.x and develop with no success. What am I missing?

```
$ cargo test
   Compiling paho-mqtt3as-sys v0.2.0 (file:///Users/gusurita/paho.mqtt.rust/paho-mqtt3as-sys)                          
error[E0063]: missing fields `cleanstart`, `connectProperties`, `onFailure5` and 2 other fields in initializer of `MQTTAsync_connectOptions`
  --> paho-mqtt3as-sys/src/lib.rs:59:3
   |
59 |         MQTTAsync_connectOptions {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^ missing `cleanstart`, `connectProperties`, `onFailure5` and 2 other fields

error[E0063]: missing fields `onFailure5`, `onSuccess5`, `properties` and 3 other fields in initializer of `MQTTAsync_responseOptions`
   --> paho-mqtt3as-sys/src/lib.rs:129:3
    |
129 |         MQTTAsync_responseOptions {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `onFailure5`, `onSuccess5`, `properties` and 3 other fields

error[E0063]: missing field `properties` in initializer of `MQTTAsync_message`
   --> paho-mqtt3as-sys/src/lib.rs:145:3
    |
145 |         MQTTAsync_message {
    |         ^^^^^^^^^^^^^^^^^ missing `properties`

error[E0063]: missing fields `onFailure5`, `onSuccess5`, `properties` and 1 other field in initializer of `MQTTAsync_disconnectOptions`
   --> paho-mqtt3as-sys/src/lib.rs:163:3
    |
163 |         MQTTAsync_disconnectOptions {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `onFailure5`, `onSuccess5`, `properties` and 1 other field

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0063`.
```

### PR DESCRIPTION
**Pull request by gallegogt**

### CODE REVIEW

**Comment by siscia** [comment]
Yeah, I got the same error.

@jnicholls , do you have something that can be compiled with a simple `cargo build` without messing too much around with dependencies?

**Comment by fpagliughi** [comment]
Thanks so much for the PR. But note that this is an official Eclipse project, so in order to contribute you would need to sign the Eclipse ECA (https://www.eclipse.org/legal/ECA.php). Hopefully that won't be a problem.

**Comment by fpagliughi** [comment]
Sorry for the slow response, I didn't seem to get notifications of several issues and PR's over the last few weeks.

As I just explained in #7, this coming version of the Rust library will specifically target Paho C v1.2.1

The Paho C library in `master` is currently unstable as the new features for MQTT v5 are being added. That is approaching a release in the near future, and so my plan is to get this version of the Rust library "done" and through the Eclipse release process, then immediately start wrapping the full new set of MQTT v5 features. I've vaguely promised to have this all done by the end of the year.

So I'm not going to accept https://github.com/eclipse/paho.mqtt.rust/pull/8/commits/97ff7f1850019d8514b1d030e46a940f7591c620 at this time, but I would like to include the other two commits concerning OS X.

If you can get the Eclipse ECA signed, that would be great, and then resubmit a PR with just the two OS X commits. Or I could cherry-pick them. Thanks.

**Comment by fpagliughi** [comment]
Actually, the new build system probably makes  34c1fe6 unnecessary. I'm just going to close this.

**Pull request closed without merging**
